# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

group :assets do
  gem 'rubyXL', '~> 3.3', '>= 3.3.26'
  gem 'inifile', '~> 3.0'
end

# gem "rails"
